# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Hoon (John) Cho
title: M.S. in Computer Science at NYU; Graduating May 2026
email: hc4338@nyu.edu
phone: (929) 707-0751

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  donburi82
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: h00n-cho
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Resume
  icon: fas fa-file-pdf
  url: https://drive.google.com/file/d/1rPoQh_8GwrrTO7HLoaKnpnPzuF0wzhCm/view?usp=sharing
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"
gtag: "G-52JQ5B0D2G"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Welcome to my personal website. Here, I share projects that do not fit on a one-page resume (available in the top-right corner of this page), ranging from early proof of concept work to longer-term projects, along with a few notes on what I enjoy outside of coding.
  
  I am motivated by building technology that solves real-world problems. While my strongest experience is in backend and ML-related work, I have been actively expanding into broader full-stack development and enjoy challenging myself in new areas.

  I am currently seeking a new-grad Software Engineer or Machine Learning Engineer role in the United States. I am most excited by opportunities to learn quickly, take ownership, and grow through meaningful engineering work.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Balloon
        caption: Mar 2026 - Present
        # link: https://www.linkedin.com/posts/hkustkriss_kriss-quant-team-fall-202324-report-vol-activity-7156470854543974400-F-76?utm_source=share&utm_medium=member_desktop
        # link_text: Report
        # additional_links:
        #   # - title: GitHub
        #   #   icon: fab fa-github
        #   #   url: https://github.com/yourname/yourrepo
        #   # - title: Pitch Deck
        #   #   icon: fas fa-file-powerpoint
        #   #   url: https://drive.google.com/file/d/1Sv1bYnMhwNGeralTKI2eWna02wPIdDwu/view?usp=sharing
        #   # - title: Demo Video
        #   #   icon: fas fa-video
        #   #   url: https://youtu.be/d3LDVcTWFB8
        #   # - title: Live demo
        #   #   icon: fas fa-globe
        #   #   url: https://example.com
        quote: >
          React Native (Expo), Node.js, Express.js, MongoDB
        description: | # this will include new lines to allow paragraphs
          - Team: Hoon Cho (Full-Stack Development), Eric Kim (UI/UX)
          - A Mobile App for Birthdays (Details TBA)
      - layout: top-middle
        title: LingBee
        caption: Mar 2026 - Present
        # link: https://www.linkedin.com/posts/hkustkriss_kriss-quant-team-fall-202324-report-vol-activity-7156470854543974400-F-76?utm_source=share&utm_medium=member_desktop
        # link_text: Report
        # additional_links:
        #   # - title: GitHub
        #   #   icon: fab fa-github
        #   #   url: https://github.com/yourname/yourrepo
        #   # - title: Pitch Deck
        #   #   icon: fas fa-file-powerpoint
        #   #   url: https://drive.google.com/file/d/1Sv1bYnMhwNGeralTKI2eWna02wPIdDwu/view?usp=sharing
        #   # - title: Demo Video
        #   #   icon: fas fa-video
        #   #   url: https://youtu.be/d3LDVcTWFB8
        #   # - title: Live demo
        #   #   icon: fas fa-globe
        #   #   url: https://example.com
        quote: >
          TBD
        description: | # this will include new lines to allow paragraphs
          - Team: Hoon Cho, Esther Lee, TBA
          - A web-based, ML-powered platform in the clinical domain (Details TBA)
      - layout: top-middle
        title: Haruna
        caption: Oct 2025 - Present
        # link: https://www.linkedin.com/posts/hkustkriss_kriss-quant-team-fall-202324-report-vol-activity-7156470854543974400-F-76?utm_source=share&utm_medium=member_desktop
        # link_text: Report
        additional_links:
          # - title: GitHub
          #   icon: fab fa-github
          #   url: https://github.com/yourname/yourrepo
          - title: Pitch Deck
            icon: fas fa-file-powerpoint
            url: https://drive.google.com/file/d/1Sv1bYnMhwNGeralTKI2eWna02wPIdDwu/view?usp=sharing
          - title: Demo Video
            icon: fas fa-video
            url: https://youtu.be/d3LDVcTWFB8
          # - title: Live demo
          #   icon: fas fa-globe
          #   url: https://example.com
        quote: >
          React Native (Expo), Node.js, Express.js, MongoDB
        description: | # this will include new lines to allow paragraphs
          - Team: Hoon Cho (Full-Stack Development), Eunsoo Cho (UI/UX, Strategy)
          - Haruna is an AI-powered wellness app for students and low-income young adults facing irregular routines, food insecurity, and mental health burdens.
      - layout: top-middle
        title: Bloom
        caption: May 2025 - Sep 2025
        # link: https://www.linkedin.com/posts/hkustkriss_kriss-quant-team-fall-202324-report-vol-activity-7156470854543974400-F-76?utm_source=share&utm_medium=member_desktop
        # link_text: Report
        additional_links:
          # - title: GitHub
          #   icon: fab fa-github
          #   url: https://github.com/yourname/yourrepo
          - title: Pitch Deck
            icon: fas fa-file-powerpoint
            url: https://drive.google.com/file/d/1NzUgNKYi2ADlxMZ6Q9Di2hWniOyhrayI/view?usp=sharing
          # - title: Demo Video
          #   icon: fas fa-video
          #   url: https://youtu.be/d3LDVcTWFB8
          # - title: Live demo
          #   icon: fas fa-globe
          #   url: https://example.com
        quote: >
          React Native (Expo), Node.js, Express.js, MongoDB
        description: | # this will include new lines to allow paragraphs
          - Team: Hoon Cho (Full-Stack Development), Eunsoo Cho (UI/UX, Strategy)
          - Bloom is an AI-powered mobile app prototype that combined career guidance, habit building, journaling, and mental wellness support for young adults, and later evolved into Haruna.
      - layout: top-middle
        title: Florise
        caption: Apr 2025
        # link: https://www.linkedin.com/posts/hkustkriss_kriss-quant-team-fall-202324-report-vol-activity-7156470854543974400-F-76?utm_source=share&utm_medium=member_desktop
        # link_text: Report
        additional_links:
          # - title: GitHub
          #   icon: fab fa-github
          #   url: https://github.com/yourname/yourrepo
          # - title: Pitch Deck
          #   icon: fas fa-file-powerpoint
          #   url: https://drive.google.com/file/d/1NzUgNKYi2ADlxMZ6Q9Di2hWniOyhrayI/view?usp=sharing
          - title: Demo Video
            icon: fas fa-video
            url: https://www.youtube.com/watch?v=YcaolYTpRow
          # - title: Live demo
          #   icon: fas fa-globe
          #   url: https://example.com
        quote: >
          React Native (Expo), Node.js, Express.js, MongoDB
        description: | # this will include new lines to allow paragraphs
          - Team: Hoon Cho (Backend Development), Eunsoo Cho (UI/UX, Strategy), Soohyeuk Choi (Frontend Development)
          - Florise is an AI-powered career discovery app for young adults navigating gap years and life uncertainty through gamified daily missions and personalized guidance, and later evolved into Bloom and Haruna.
          - Florise was selected as a semi-finalist at NYU Tandon’s [2025 Capstone Competition](https://engineering.nyu.edu/news/future-was-display-tandons-2025-capstone-competition), where our team was one of six teams chosen to deliver a 10-minute pitch to industry judges.
      - layout: top-middle
        title: TravSum
        caption: Mar 2025
        # link: https://www.linkedin.com/posts/hkustkriss_kriss-quant-team-fall-202324-report-vol-activity-7156470854543974400-F-76?utm_source=share&utm_medium=member_desktop
        # link_text: Report
        additional_links:
          # - title: GitHub
          #   icon: fab fa-github
          #   url: https://github.com/yourname/yourrepo
          # - title: Pitch Deck
          #   icon: fas fa-file-powerpoint
          #   url: https://drive.google.com/file/d/1NzUgNKYi2ADlxMZ6Q9Di2hWniOyhrayI/view?usp=sharing
          - title: Demo Video
            icon: fas fa-video
            url: https://www.youtube.com/watch?v=Ib4evIDuKOk
          # - title: Live demo
          #   icon: fas fa-globe
          #   url: https://example.com
        quote: >
          React Native (Expo), Node.js, Express.js, MongoDB
        description: | # this will include new lines to allow paragraphs
          - Team: Hoon Cho (Backend Development), Eunsoo Cho (UI/UX, Strategy), Christopher Park (Frontend Development), Yujin Yi (Frontend Development)
          - TravSum is an AI-powered travel storytelling app that transforms trip photos into themed highlight videos by extracting image metadata, categorizing moments, and compiling them into a dynamic visual summary.
          - TravSum was one of the winners at Tech@NYU’s 2025 Buildathon and received the Adobe-sponsored Best UI/UX Design award.
  
  - title: Research Interests
    layout: text
    content: | # this will include new lines to allow paragraphs
      I am broadly interested in building machine learning systems that are reliable, equitable, and socially responsible across a wide range of decision-making contexts. In particular, I want to understand how models arrive at their decisions, when those decisions can be justified, and why models fail.
      
      Much of my current research focuses on large language models (LLMs), especially questions around interpretability, reliability, and fairness. My main motivation, however, is not LLMs in themselves, but the broader challenge of ensuring that machine learning systems are dependable and responsible in practice.

  - title: Research # Title for the section
    layout: list # Type of content section (list/text)
    content:
      # - layout: left
      #   description: |
      #     I am particularly interested in understanding how models form and justify their decisions, why they fail, and how these failures reveal underlying patterns in the data.
      - layout: top-middle
        title: Disentangling Instruction Following vs. Reasoning in LLMs
        caption: Feb 2026 - Present
        # link: https://www.linkedin.com/posts/hkustkriss_kriss-quant-team-fall-202324-report-vol-activity-7156470854543974400-F-76?utm_source=share&utm_medium=member_desktop
        # link_text: Report
        # additional_links:
        #   # - title: GitHub
        #   #   icon: fab fa-github
        #   #   url: https://github.com/yourname/yourrepo
        #   # - title: Pitch Deck
        #   #   icon: fas fa-file-powerpoint
        #   #   url: https://drive.google.com/file/d/1Sv1bYnMhwNGeralTKI2eWna02wPIdDwu/view?usp=sharing
        #   # - title: Demo Video
        #   #   icon: fas fa-video
        #   #   url: https://youtu.be/d3LDVcTWFB8
        #   # - title: Live demo
        #   #   icon: fas fa-globe
        #   #   url: https://example.com
        # quote: >
        #   React Native (Expo), Node.js, Express.js, MongoDB
        description: | # this will include new lines to allow paragraphs
          - Personal work
      - layout: top-middle
        title: Reasoning Consistency & Validity of LLMs
        caption: Jun 2025 - Present
        # link: https://www.linkedin.com/posts/hkustkriss_kriss-quant-team-fall-202324-report-vol-activity-7156470854543974400-F-76?utm_source=share&utm_medium=member_desktop
        # link_text: Report
        # additional_links:
        #   # - title: GitHub
        #   #   icon: fab fa-github
        #   #   url: https://github.com/yourname/yourrepo
        #   # - title: Pitch Deck
        #   #   icon: fas fa-file-powerpoint
        #   #   url: https://drive.google.com/file/d/1Sv1bYnMhwNGeralTKI2eWna02wPIdDwu/view?usp=sharing
        #   # - title: Demo Video
        #   #   icon: fas fa-video
        #   #   url: https://youtu.be/d3LDVcTWFB8
        #   # - title: Live demo
        #   #   icon: fas fa-globe
        #   #   url: https://example.com
        # quote: >
        #   React Native (Expo), Node.js, Express.js, MongoDB
        description: | # this will include new lines to allow paragraphs
          - Collaborators: Dr. [Emily Black](https://emblack.github.io/) (PI), Falaah Arif Khan
      - layout: top-middle
        title: High-resolution Air Temperature Prediction in LA
        caption: Oct 2024 - Present
        # link: https://www.linkedin.com/posts/hkustkriss_kriss-quant-team-fall-202324-report-vol-activity-7156470854543974400-F-76?utm_source=share&utm_medium=member_desktop
        # link_text: Report
        # additional_links:
        #   # - title: GitHub
        #   #   icon: fab fa-github
        #   #   url: https://github.com/yourname/yourrepo
        #   # - title: Pitch Deck
        #   #   icon: fas fa-file-powerpoint
        #   #   url: https://drive.google.com/file/d/1Sv1bYnMhwNGeralTKI2eWna02wPIdDwu/view?usp=sharing
        #   # - title: Demo Video
        #   #   icon: fas fa-video
        #   #   url: https://youtu.be/d3LDVcTWFB8
        #   # - title: Live demo
        #   #   icon: fas fa-globe
        #   #   url: https://example.com
        # quote: >
        #   React Native (Expo), Node.js, Express.js, MongoDB
        description: | # this will include new lines to allow paragraphs
          - Collaborators: Dr. [Yi Yin](https://as.nyu.edu/faculty/yi-yin.html) (PI)
  
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      When I’m not coding, you’ll usually find me doing one of these:
      - Playing the [piano](https://youtu.be/eR-yIzAl9n8?si=VtU_EHQiUcs3dTO2&t=3081)
      - Playing squash
      - Watching films
      - Cooking
      - Reading (new habit)

# Footer
footer_show_references: true
# references_title:  (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
